// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjBjOMWrB3F2n2o-DWz_4X-YMUfIUdJ08',
    appId: '1:758116781229:web:cc748ab34888e611ad8a24',
    messagingSenderId: '758116781229',
    projectId: 'flutter-app-distribution-20825',
    authDomain: 'flutter-app-distribution-20825.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-20825.appspot.com',
    measurementId: 'G-2RS63BRCXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_mWcGuT3DgqjhcMPHklkUZK4KoXRX0Xw',
    appId: '1:758116781229:android:69fdfda71543e56fad8a24',
    messagingSenderId: '758116781229',
    projectId: 'flutter-app-distribution-20825',
    storageBucket: 'flutter-app-distribution-20825.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRRKqk2jmnAPunFwkl8vZZCnPqJyuSZJ8',
    appId: '1:758116781229:ios:901ebddcf89c0c42ad8a24',
    messagingSenderId: '758116781229',
    projectId: 'flutter-app-distribution-20825',
    storageBucket: 'flutter-app-distribution-20825.appspot.com',
    iosBundleId: 'com.example.flutterCompleteFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRRKqk2jmnAPunFwkl8vZZCnPqJyuSZJ8',
    appId: '1:758116781229:ios:901ebddcf89c0c42ad8a24',
    messagingSenderId: '758116781229',
    projectId: 'flutter-app-distribution-20825',
    storageBucket: 'flutter-app-distribution-20825.appspot.com',
    iosBundleId: 'com.example.flutterCompleteFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjBjOMWrB3F2n2o-DWz_4X-YMUfIUdJ08',
    appId: '1:758116781229:web:24326ed3609c916ead8a24',
    messagingSenderId: '758116781229',
    projectId: 'flutter-app-distribution-20825',
    authDomain: 'flutter-app-distribution-20825.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-20825.appspot.com',
    measurementId: 'G-TZ4RZQ2V8Y',
  );
}
